---
- name: BACKUP ALL CONFIGS
  hosts: vyos-servers
  gather_facts: false

  tasks:

  #  - name: RETRIEVE CONFIGURATION
  #    cli_command:  
  #      command: "{{backup}}"
  #    register: backup

 #   - name: MOVE TO FILE
 #     copy:
 #       content: "{{backup.stdout}}"
 #       dest: "{{inventory_hostname}}.backup"
    
    - name: configurable backup 
      vyos_config:
        src: /home/user/vyos.cfg
        backup: yes
